import 'package:flutter_test/flutter_test.dart';
import 'package:layrz_models/layrz_models.dart';

void main() {
  test(
    "BillingPlan.fromJson",
    () {
      final data = {
        "id": "33",
        "reconnectionPercent": 0,
        "reconnectionMaximum": 3,
        "reconnectionIncidents": 0,
        "maxAssets": 99999,
        "maxDevices": 99999,
        "maxUsers": 99999,
        "maxOutboundServices": 99999,
        "maxFunctions": 99999,
        "maxApps": 99999,
        "allowedAppsIds": ["1", "2", "11", "22"],
        "allowedAlgorithmsIds": [],
        "allowedInboundProtocolsIds": [
          "40",
          "41",
          "23",
          "39",
          "55",
          "43",
          "46",
          "42",
          "44",
          "20",
          "21",
          "47",
          "65",
          "49",
          "50",
          "51",
          "54",
          "18",
          "19",
          "24",
          "25",
          "26",
          "29",
          "45",
          "14",
          "64",
          "10",
          "2",
          "13",
          "53",
          "32",
          "1",
          "3",
          "4",
          "5",
          "6",
          "8",
          "11",
          "34",
          "35",
          "33",
          "12",
          "36",
          "38",
          "37",
          "7",
          "15",
          "16",
          "22",
          "30",
          "31",
          "27",
          "17",
          "28",
          "48",
          "52"
        ],
        "allowedOutboundProtocolsIds": [
          "1",
          "2",
          "3",
          "4",
          "8",
          "9",
          "11",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
          "41",
          "42",
          "43",
          "44",
          "45",
          "46",
          "47",
          "48"
        ],
        "allowedVisionProtocolsIds": [],
        "allowedExchangeProtocolsIds": [],
      };
      final bill = BillingPlan.fromJson(data);

      expect(bill, isA<BillingPlan>());
    },
  );
}
