image: registry.gitlab.com/goldenm-software/layrz/docker-containers/flutter-web-builder:flutter-3.10.5

stages:
  - deploy

deploy:
  stage: deploy

  before_script:
    - export PUB_PROJECT_ID=$PUB_PROJECT_ID
    - export PUB_PRIVATE_KEY_ID=$PUB_PRIVATE_KEY_ID
    - export PUB_PRIVATE_KEY=$PUB_PRIVATE_KEY
    - export PUB_CLIENT_EMAIL=$PUB_CLIENT_EMAIL
    - export PUB_CLIENT_ID=$PUB_CLIENT_ID
    - export PUB_CLIENT_EMAIL_CLIENT=$PUB_CLIENT_EMAIL_CLIENT
    - python3 /usr/bin/key_gen
    - gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json
    - gcloud auth print-identity-token --audiences=https://pub.dev | dart pub token add stdin https://pub.dev

  script:
    - dart pub publish -f

  after_script:
    - dart pub token remove https://pub.dev

  tags:
    - saas-linux-small-amd64

  only:
    - main
