image: registry.gitlab.com/goldenm-software/layrz/docker-containers/flutter-web-builder:flutter-3.10.5

stages:
  - deploy

deploy:
  stage: deploy

  before_script:
    - gcloud auth activate-service-account --key-file=$PUB_TOKEN
    - gcloud auth print-identity-token --audiences=https://pub.dev | dart pub token add https://pub.dev

  script:
    - dart pub publish -f

  after_script:
    - dart pub token remove https://pub.dev

  tags:
    - saas-linux-small-amd64

  only:
    - main
