include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - lib/utils/src/icons.dart

  # Ignore invalid_annotation_target
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    unreachable_switch_default: ignore

formatter:
  page_width: 120