part of '../app.dart';

@freezed
abstract class RegisteredApp with _$RegisteredApp {
  const RegisteredApp._();

  const factory RegisteredApp({
    /// [id] is the unique identifier of the app.
    required String id,

    /// [name] is the name of the app. It's a fixed name, not a translation key
    required String name,

    /// [technology] is the technology of the app.
    @JsonKey(unknownEnumValue: AppTechnology.flutter) @Default(AppTechnology.flutter) AppTechnology technology,

    /// [legalInformation] is the legal information of the app.
    AppLegal? legalInformation,

    /// [designInformation] is the design information of the app.
    AppDesign? designInformation,
    required String nickname,
    bool? isCustomized,
    List<AppInstance>? instances,
    List<Asset>? importedAssets,
    List<Device>? importedDevices,
    List<User>? importedUsers,
    List<User>? keychain,
    required String sourceId,

    /// [owner] is the owner of the app.
    /// !Important: This field is only available when the query is from `/goldenm/graphql`
    User? owner,

    /// [allowedReports] is the list of reports allowed to be generated by the app.
    List<CustomReport>? allowedReports,

    /// [fixedWorkspaceId] is the id of the fixed workspace of the app.
    String? fixedWorkspaceId,

    /// [fixedWorkspace] is the fixed workspace of the app.
    Workspace? fixedWorkspace,

    /// [authorizedLayers] is the list of layers authorized to be used by the app.
    @Default([]) List<MapLayer> authorizedLayers,

    /// [iosPushSecrets] is the decrypted iOS Firebase credentials for layrz_push
    PushSecrets? iosPushSecrets,

    /// [androidPushSecrets] is the decrypted Android Firebase credentials for layrz_push
    PushSecrets? androidPushSecrets,

    /// true when the backend holds service-account push credentials; content never exposed.
    bool? hasSvcPushSecrets,
  }) = _RegisteredApp;

  factory RegisteredApp.fromJson(Map<String, dynamic> json) => _$RegisteredAppFromJson(json);

  /// [fetchAll] fetches all registered apps from the server
  /// It returns a list of [RegisteredApp] with the required contextual information
  static Future<List<RegisteredApp>> fetchAll({
    /// [apiToken] is the API token to use for authentication. You can get one using the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// [uri] is the GraphQL endpoint to use
    required Uri uri,

    /// [onResponse] is the callback to call when the response is received
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlQuery(
          variables: [],
          name: 'fetchRegisteredApps',
        )..add(
          GqlField(name: 'registeredApps', args: {})
            ..add(GqlField(name: 'status'))
            ..add(
              GqlField(name: 'result')
                ..add(GqlField(name: 'id'))
                ..add(GqlField(name: 'name'))
                ..add(GqlField(name: 'nickname'))
                ..add(GqlField(name: 'designInformation', fragment: AppDesign.reducedFragment))
                ..add(
                  GqlField(name: 'instances')
                    ..add(GqlField(name: 'id'))
                    ..add(GqlField(name: 'appId'))
                    ..add(GqlField(name: 'platform'))
                    ..add(GqlField(name: 'host'))
                    ..add(GqlField(name: 'status')),
                ),
            ),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/fetchAll(): No response from server");
        return [];
      }

      final result = data['data']['registeredApps'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/fetchAll(): No result from server");
        return [];
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return [];
      }

      return (result['result'] as List<dynamic>?)
              ?.map((e) => RegisteredApp.fromJson(Map<String, dynamic>.from(e as Map)))
              .toList() ??
          [];
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/fetchAll(): General exception => $e\n$stack");
      return [];
    }
  }

  /// [fetch] fetches a single registered app by ID from the server.
  /// It returns a [RegisteredApp] with the required contextual information or null on error.
  static Future<RegisteredApp?> fetch({
    required String id,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlQuery(
          variables: [
            GqlVariable(name: 'id', type: .id, isRequired: true, value: id),
          ],
          name: 'fetchRegisteredApp',
        )..add(
          GqlField(name: 'registeredApps', args: {'id': 'id'})
            ..add(GqlField(name: 'status'))
            ..add(GqlField(name: 'result', fragment: fragment)),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/fetch(): No response from server");
        return null;
      }

      final result = data['data']['registeredApps'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/fetch(): No result from server");
        return null;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return null;
      }

      final resultList = result['result'] as List<dynamic>?;
      if (resultList == null || resultList.isEmpty) {
        Log.warning("layrz_models/RegisteredApp/fetch(): No result in list");
        return null;
      }
      return RegisteredApp.fromJson(Map<String, dynamic>.from(resultList.first as Map));
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/fetch(): General exception => $e\n$stack");
      return null;
    }
  }

  /// [setPushSecrets] sets push notification secrets for the app.
  /// Accepts optional Firebase secrets for iOS, Android, and service account.
  /// Returns true on success, false on error.
  static Future<bool> setPushSecrets({
    required String appId,
    String? iosPushSecrets,
    String? androidPushSecrets,
    String? svcPushSecrets,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final variables = <GqlVariable>[
        GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
      ];

      if (iosPushSecrets != null) {
        variables.add(GqlVariable(name: 'iosPushSecrets', type: .string, isRequired: false, value: iosPushSecrets));
      }
      if (androidPushSecrets != null) {
        variables.add(
          GqlVariable(name: 'androidPushSecrets', type: .string, isRequired: false, value: androidPushSecrets),
        );
      }
      if (svcPushSecrets != null) {
        variables.add(GqlVariable(name: 'svcPushSecrets', type: .string, isRequired: false, value: svcPushSecrets));
      }

      final response = await connector.perform(
        GqlMutation(
          variables: variables,
          name: 'setPushSecrets',
        )..add(
          GqlField(
            name: 'setPushSecrets',
            args: {
              'appId': 'appId',
              if (iosPushSecrets != null) 'iosPushSecrets': 'iosPushSecrets',
              if (androidPushSecrets != null) 'androidPushSecrets': 'androidPushSecrets',
              if (svcPushSecrets != null) 'svcPushSecrets': 'svcPushSecrets',
            },
          )..add(GqlField(name: 'status')),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/setPushSecrets(): No response from server");
        return false;
      }

      final result = data['data']['setPushSecrets'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/setPushSecrets(): No result from server");
        return false;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/setPushSecrets(): General exception => $e\n$stack");
      return false;
    }
  }

  /// [grantAccessToApp] grants a user access to the app.
  /// Returns true on success, false on error.
  static Future<bool> grantAccessToApp({
    required String userId,
    required String appId,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(name: 'userId', type: .id, isRequired: true, value: userId),
          ],
          name: 'grantAccessToApp',
        )..add(
          GqlField(name: 'grantAccessToApp', args: {'appId': 'appId', 'userId': 'userId'})
            ..add(GqlField(name: 'status')),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/grantAccessToApp(): No response from server");
        return false;
      }

      final result = data['data']['grantAccessToApp'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/grantAccessToApp(): No result from server");
        return false;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/grantAccessToApp(): General exception => $e\n$stack");
      return false;
    }
  }

  /// [grantMultipleAccessToApp] grants multiple users access to the app.
  /// Returns true on success, false on error.
  static Future<bool> grantMultipleAccessToApp({
    required List<String> usersIds,
    required String appId,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(
              name: 'userIds',
              type: .list(of: .id, isRequired: true),
              isRequired: true,
              value: usersIds,
            ),
          ],
          name: 'grantMultipleAccessToApp',
        )..add(
          GqlField(
            name: 'grantMultipleAccessToApp',
            args: {'appId': 'appId', 'userIds': 'userIds'},
          )..add(GqlField(name: 'status')),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/grantMultipleAccessToApp(): No response from server");
        return false;
      }

      final result = data['data']['grantMultipleAccessToApp'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/grantMultipleAccessToApp(): No result from server");
        return false;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/grantMultipleAccessToApp(): General exception => $e\n$stack");
      return false;
    }
  }

  /// [revokeAccessToApp] revokes user access to the app.
  /// Returns true on success, false on error.
  static Future<bool> revokeAccessToApp({
    required String userId,
    required String appId,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(name: 'userId', type: .id, isRequired: true, value: userId),
          ],
          name: 'revokeAccessToApp',
        )..add(
          GqlField(name: 'revokeAccessToApp', args: {'appId': 'appId', 'userId': 'userId'})
            ..add(GqlField(name: 'status')),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/revokeAccessToApp(): No response from server");
        return false;
      }

      final result = data['data']['revokeAccessToApp'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/revokeAccessToApp(): No result from server");
        return false;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/revokeAccessToApp(): General exception => $e\n$stack");
      return false;
    }
  }

  /// [importAssetsIntoApp] imports assets into the app.
  /// Returns true on success, false on error.
  static Future<bool> importAssetsIntoApp({
    required List<String> assetsIds,
    required String appId,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(
              name: 'assetsIds',
              type: .list(of: .id, isRequired: true),
              isRequired: true,
              value: assetsIds,
            ),
          ],
          name: 'importAssetsIntoApp',
        )..add(
          GqlField(
            name: 'importAssetsIntoApp',
            args: {'appId': 'appId', 'assetsIds': 'assetsIds'},
          )..add(GqlField(name: 'status')),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/importAssetsIntoApp(): No response from server");
        return false;
      }

      final result = data['data']['importAssetsIntoApp'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/importAssetsIntoApp(): No result from server");
        return false;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/importAssetsIntoApp(): General exception => $e\n$stack");
      return false;
    }
  }

  /// [revokeAssetsFromApp] revokes assets from the app.
  /// Returns true on success, false on error.
  static Future<bool> revokeAssetsFromApp({
    required List<String> assetsIds,
    required String appId,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(
              name: 'assetsIds',
              type: .list(of: .id, isRequired: true),
              isRequired: true,
              value: assetsIds,
            ),
          ],
          name: 'revokeAssetsFromApp',
        )..add(
          GqlField(
            name: 'revokeAssetsFromApp',
            args: {'appId': 'appId', 'assetsIds': 'assetsIds'},
          )..add(GqlField(name: 'status')),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/revokeAssetsFromApp(): No response from server");
        return false;
      }

      final result = data['data']['revokeAssetsFromApp'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/revokeAssetsFromApp(): No result from server");
        return false;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/revokeAssetsFromApp(): General exception => $e\n$stack");
      return false;
    }
  }

  /// [importDevicesIntoApp] imports devices into the app.
  /// Returns true on success, false on error.
  static Future<bool> importDevicesIntoApp({
    required List<String> devicesIds,
    required String appId,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(
              name: 'devicesIds',
              type: .list(of: .id, isRequired: true),
              isRequired: true,
              value: devicesIds,
            ),
          ],
          name: 'importDevicesIntoApp',
        )..add(
          GqlField(
            name: 'importDevicesIntoApp',
            args: {'appId': 'appId', 'devicesIds': 'devicesIds'},
          )..add(GqlField(name: 'status')),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/importDevicesIntoApp(): No response from server");
        return false;
      }

      final result = data['data']['importDevicesIntoApp'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/importDevicesIntoApp(): No result from server");
        return false;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/importDevicesIntoApp(): General exception => $e\n$stack");
      return false;
    }
  }

  /// [revokeDevicesFromApp] revokes devices from the app.
  /// Returns true on success, false on error.
  static Future<bool> revokeDevicesFromApp({
    required List<String> devicesIds,
    required String appId,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(
              name: 'devicesIds',
              type: .list(of: .id, isRequired: true),
              isRequired: true,
              value: devicesIds,
            ),
          ],
          name: 'revokeDevicesFromApp',
        )..add(
          GqlField(
            name: 'revokeDevicesFromApp',
            args: {'appId': 'appId', 'devicesIds': 'devicesIds'},
          )..add(GqlField(name: 'status')),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/revokeDevicesFromApp(): No response from server");
        return false;
      }

      final result = data['data']['revokeDevicesFromApp'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/revokeDevicesFromApp(): No result from server");
        return false;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/revokeDevicesFromApp(): General exception => $e\n$stack");
      return false;
    }
  }

  /// [registerWithoutCustomization] registers a new app without customization on the server.
  /// Returns the created [RegisteredApp] on success, null on error.
  static Future<RegisteredApp?> registerWithoutCustomization({
    required Map<String, dynamic> data,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(
              name: 'data',
              type: GqlVariableType.input(of: 'AppWithoutCustomizationInput'),
              isRequired: true,
              value: data,
            ),
          ],
          name: 'registerAppWithoutCustomization',
        )..add(
          GqlField(name: 'registerAppWithoutCustomization', args: {'data': 'data'})
            ..add(GqlField(name: 'status'))
            ..add(GqlField(name: 'result', fragment: fragment)),
        ),
      );

      final responseData = response.data;
      if (responseData == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/registerWithoutCustomization(): No response from server");
        return null;
      }

      final result = responseData['data']['registerAppWithoutCustomization'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/registerWithoutCustomization(): No result from server");
        return null;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return null;
      }

      final resultList = result['result'] as List<dynamic>?;
      if (resultList == null || resultList.isEmpty) {
        Log.warning("layrz_models/RegisteredApp/registerWithoutCustomization(): No result in list");
        return null;
      }
      return RegisteredApp.fromJson(Map<String, dynamic>.from(resultList.first as Map));
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/registerWithoutCustomization(): General exception => $e\n$stack");
      return null;
    }
  }

  /// [registerWithCustomization] registers a new app with customization on the server.
  /// Returns the created [RegisteredApp] on success, null on error.
  static Future<RegisteredApp?> registerWithCustomization({
    required Map<String, dynamic> data,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(
              name: 'data',
              type: GqlVariableType.input(of: 'AppInput'),
              isRequired: true,
              value: data,
            ),
          ],
          name: 'registerAppWithCustomization',
        )..add(
          GqlField(name: 'registerAppWithCustomization', args: {'data': 'data'})
            ..add(GqlField(name: 'status'))
            ..add(GqlField(name: 'result', fragment: fragment)),
        ),
      );

      final responseData = response.data;
      if (responseData == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/registerWithCustomization(): No response from server");
        return null;
      }

      final result = responseData['data']['registerAppWithCustomization'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/registerWithCustomization(): No result from server");
        return null;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return null;
      }

      final resultList = result['result'] as List<dynamic>?;
      if (resultList == null || resultList.isEmpty) {
        Log.warning("layrz_models/RegisteredApp/registerWithCustomization(): No result in list");
        return null;
      }
      return RegisteredApp.fromJson(Map<String, dynamic>.from(resultList.first as Map));
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/registerWithCustomization(): General exception => $e\n$stack");
      return null;
    }
  }

  /// [edit] edits an existing app on the server.
  /// Returns the updated [RegisteredApp] on success, null on error.
  static Future<RegisteredApp?> edit({
    required String id,
    required Map<String, dynamic> data,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(name: 'id', type: .id, isRequired: true, value: id),
            GqlVariable(
              name: 'data',
              type: GqlVariableType.input(of: 'AppInput'),
              isRequired: true,
              value: data,
            ),
          ],
          name: 'editApp',
        )..add(
          GqlField(name: 'editApp', args: {'id': 'id', 'data': 'data'})
            ..add(GqlField(name: 'status'))
            ..add(GqlField(name: 'result', fragment: fragment)),
        ),
      );

      final responseData = response.data;
      if (responseData == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/edit(): No response from server");
        return null;
      }

      final result = responseData['data']['editApp'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/edit(): No result from server");
        return null;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return null;
      }

      final resultList = result['result'] as List<dynamic>?;
      if (resultList == null || resultList.isEmpty) {
        Log.warning("layrz_models/RegisteredApp/edit(): No result in list");
        return null;
      }
      return RegisteredApp.fromJson(Map<String, dynamic>.from(resultList.first as Map));
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/edit(): General exception => $e\n$stack");
      return null;
    }
  }

  /// [delete] deletes an app from the server by ID.
  /// Returns true on success, false on error.
  static Future<bool> delete({
    required String id,
    required String apiToken,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.perform(
        GqlMutation(
          variables: [
            GqlVariable(name: 'id', type: .id, isRequired: true, value: id),
          ],
          name: 'deleteApp',
        )..add(
          GqlField(name: 'deleteApp', args: {'id': 'id'})..add(GqlField(name: 'status')),
        ),
      );

      final responseData = response.data;
      if (responseData == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/delete(): No response from server");
        return false;
      }

      final result = responseData['data']['deleteApp'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/delete(): No result from server");
        return false;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/delete(): General exception => $e\n$stack");
      return false;
    }
  }

  /// [load] loads a registered app from the server by ID.
  /// Returns the loaded [RegisteredApp] on success, null on error.
  static Future<RegisteredApp?> load({
    required String appId,
    required AppPlatform platform,
    required AppTechnology technology,
    required Uri uri,
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri);
    try {
      final response = await connector.perform(
        GqlQuery(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(name: 'platform', type: .string, isRequired: true, value: platform.name),
            GqlVariable(name: 'technology', type: .string, isRequired: true, value: technology.name),
          ],
        )..add(
          GqlField(name: 'loadApp', args: {'platform': 'platform', 'technology': 'technology', 'appId': 'appId'})
            ..add(GqlField(name: 'status'))
            ..add(
              GqlField(name: 'result')
                ..add(GqlField(name: 'id'))
                ..add(GqlField(name: 'name'))
                ..add(GqlField(name: 'nickname'))
                ..add(GqlField(name: 'technology'))
                ..add(GqlField(name: 'sourceId'))
                ..add(GqlField(name: 'legalInformation', fragment: AppLegal.fragment))
                ..add(GqlField(name: 'designInformation', fragment: AppDesign.fragment)),
            ),
        ),
      );

      final data = response.data;
      if (data == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/load(): No response from server");
        return null;
      }

      final result = data['data']['loadApp'];
      if (result == null) {
        onResponse?.call(ApiStatus.internalError.toJson());
        Log.error("layrz_models/RegisteredApp/load(): No result from server");
        return null;
      }

      final status = ApiStatus.fromJson(result['status']);
      if (status != ApiStatus.ok) {
        onResponse?.call(status.toJson());
        return null;
      }

      return result['result'] != null
          ? RegisteredApp.fromJson(Map<String, dynamic>.from(result['result'] as Map))
          : null;
    } catch (e, stack) {
      Log.critical("layrz_models/RegisteredApp/load(): General exception => $e\n$stack");
      return null;
    }
  }

  /// [fragment] is the GqlFragment for a registered app.
  static GqlFragment get fragment => GqlFragment(name: 'registeredAppFragment', onType: 'RegisteredApp')
    ..add(GqlField(name: 'id'))
    ..add(GqlField(name: 'name'))
    ..add(GqlField(name: 'nickname'))
    ..add(GqlField(name: 'isCustomized'))
    ..add(GqlField(name: 'technology'))
    ..add(GqlField(name: 'sourceId'))
    ..add(GqlField(name: 'instances', fragment: AppInstance.fragment))
    ..add(GqlField(name: 'designInformation', fragment: AppDesign.fragment))
    ..add(
      GqlField(name: 'legalInformation')
        ..add(GqlField(name: 'companyName'))
        ..add(GqlField(name: 'companyUrl'))
        ..add(GqlField(name: 'privacyPolicy')),
    )
    ..add(GqlField(name: 'iosPushSecrets', fragment: PushSecrets.fragment))
    ..add(GqlField(name: 'androidPushSecrets', fragment: PushSecrets.fragment))
    ..add(GqlField(name: 'hasSvcPushSecrets'));
}
