part of '../ble.dart';

@freezed
class BleDevice with _$BleDevice {
  const BleDevice._();

  /// [BleDevice] is the representation of a BLE device.
  const factory BleDevice({
    /// [macAddress] is the MAC address of the BLE device.
    /// Be careful, on Apple ecosystem, the MAC address is not the real identifier, is a generated by the platform
    /// and is hidden from the developer.
    required String macAddress,

    /// [name] is the name of the BLE device.
    /// Can be null if the device does not have a name or is not broadcasted.
    String? name,

    /// [rssi] is the signal strength of the BLE device.
    /// Can be null if the device does not have a signal strength due to a platform limitation.
    int? rssi,

    /// [advertisementData] is the advertisement data of the BLE device.
    /// Can be null if the device does not have advertisement data or is not broadcasted.
    List<int>? advertisementData,
  }) = _BleDevice;

  factory BleDevice.fromJson(Map<String, dynamic> json) => _$BleDeviceFromJson(json);
}
